//:source-highlighter: coderay

:jbake-type: page
:jbake-status: published

:sectnums: yes
:linkattrs: true

= Apache Tamaya: Download

The latest release is Apache Tamaya {tamaya_version_released}.
You can download it it from the
http://www.apache.org/dyn/closer.cgi/incubator/tamaya[Apache Software Foundation Distribution Directory^].

The release notes for each release of Apache Tamaya
can be found at the link:history.html[release history page].

== Current Source Code

Downloading of the the current state of the project can be done by

* cloning the https://github.com/apache/incubator-tamaya[GitHub repo^]
* Github also provides an easy way to dowload the current project source as zip archive.
// @todo * Cloning the Apache source tree, see link:3[source section]. source.html


== Maven Dependencies

// @todo
// @todo Details are available <a href="documentation/#_project_configuration_without_maven">here</a>.


// @todo Source highlighting does not work currently.
//
[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>{tamaya_mvn_group_id}</groupId>
    <artifactId>tamaya-api</artifactId>
    <version>{tamaya_version_released}</version>
</dependency>
<dependency>
    <groupId>{tamaya_mvn_group_id}</groupId>
    <artifactId>tamaya-core</artifactId>
    <version>{tamaya_version_released}</version>
</dependency>
----


== Previous Releases

All previous releases can also be found at the
https://archive.apache.org/dist/incubator/tamaya/[Apache Software Foundation Distribution Archive^].
In our link:history.html[release history overview] you can find all previous releases of Tamaya.

== Verifying Releases

It is essential that you verify the integrity of any downloaded files using
the PGP or MD5 signatures.  For more information on signing artifacts and
why we do it, check out the
https://www.apache.org/dev/release-signing.html[Release Signing FAQ^].

The PGP signatures can be verified using PGP or GPG. First download the
https://www.apache.org/dist/incubator/tamaya/KEYS[KEYS file^]
as well as the asc signature file for the artifact. Make sure you get
these files from the
https://www.apache.org/dist/incubator/tamaya/[main distribution directory^]
rather than from a
https://www.apache.org/dyn/closer.cgi/incubator/tamaya/[mirror^].
Then verify the signatures using e.g.:

[source,shell]
----
$ pgpk -a KEYS
$ pgpv tamaya-project-1.2.0-source-release.zip.asc
----

or
[source,shell]
----
$ pgp -ka KEYS
$ pgp tamaya-project-1.2.0-source-release.zip.asc
----

or

[source,shell]
----
$ gpg --import KEYS
$ gpg --verify tamaya-project-1.2.0-source-release.zip.asc
----
