:jbake-type: page
:jbake-status: published

:sectnums: yes

= Apache Tamaya Release Guide

This document describes how to perform a release of Apache Tamaya during
its incubation. It contains a step by step description of each step,
so everybody in the commiters's team will be able to perform
the release procedure during the incubation phase.


#Performing a release requires several steps. This document describes each
#step, so everybody in the committer's
#team should be able to perform the release procedure.

== Prerequisites

This section describes the prerequisite which must be given to
perform the release procedure.

["upperroman"]

. Subversion client, needed to upload the source distribution.
. Git
. A valid GPG key, needed to sign all artifacts created during
  the release process.


== Performing the release

=== Tell the others you would proceed with the release procedure

The first step is to announce on developer mailing list that
you plan to release a new version of Tamaya API&Core as well
as of the Tamaya Extensions.

Take the mail template below, adapt it if necessary, an send it
to mailto:dev@tamaya.incubator.apache.org[dev@tamaya.incubator.apache.org].



.Subject of the announcement of an upcomming release
----
Starting with the preparation of the next release of <<project>>
----

.Body of the announcement of an upcomming release.
[listing,text]
----
Dear all,

If there are no objections, I'll start with the first steps for
the next release of <<project>> (review, documentation,...).
It would be great to start with the release procedure next week.

Best regards,
<<your name>>
----

Don't expect that everyone will response immediately as we all are very
busy. So be patient with you team members. Meanwhile you can
proceed with the release preparations.

=== Check if everything is ready

The following items must be done before you can start with the
actual release process.

. Check if the build chains in
  https://builds.apache.org/view/Tamaya/[Apache's Jenkins^]
  of the project in to be released are fine and where are
  no problems with the build and quality of the project.
. Ensure that all
  https://issues.apache.org/jira/projects/TAMAYA[JIRA^] issues
  targeting the upcomming release are resolved.
  If not, get in contact with the issue assignee or the reporter to
  check
  .. if the issue can be postponed for the next release
  .. how long it takes to resolve it and if someone can help.


=== Prepare the release notes

* Create release notes and commit them to the `/readme/`
  directory of the project. The file name of the release
  notes document should be `ReleaseNotes-[version].html`.

// Question: How to handle the problem that we actually have
// to distributions? One is API&Core and the second is the
// extension distribution? At the moment the release notes
// are part of API&Core. The Extensions contain only a
// reference to API&Core
// Oliver B. Fischer, 2017-07-08
//


=== Preparing the vote of the PPMC on the release

If you are sure that everything is ready for the
next release you can start the vote of the PPMC
on the proposed release.

[IMPORTANT]
====
Keep in mind that preparing the release
really means only to prepare the release by
uploading it to the dev area of the
https://dist.apache.org[distribution
server of the Apache project^] and to a staging
repository of https://repository.apache.org[Apache's Nexus^].

You must not publish the artifacts created during
the preparation of the release until the IPMC as well
as the PPMC of Apache Tamaya have approved the release.
====

Before you can present the proposed release to the
IPMC of the Apache Incubator, the proposd release must be
approved by the PPMC of the Tamaya project.

Therefore you must run a vote on the proposed release
by creating a vote candidat in the Git repository of
the project, uploading the source distribution
to the dev area of the distribution server of the Apache
project and uploading the Maven artifacts to a staging
repository in Apache's Nexus. This sounds complicated
but it isn't that complicated if you follow the steps
of this guide.

---
Rewritten until here
---


//==== Creating a vote candidat in the Git repository


* Create a release branch in git and switch to this branch:



=== Using the Release Plugin

For performing the release you can use the maven release plugin:

[listing,text]
----
$ git checkout -b vote-tamaya-[release version]
$ export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=200m"
$ mvn release:prepare -DdryRun=true -DperformRelease=true
# optionally pass GPG params for signing with: -Darguments="-Dgpg.keyname=1336D3E6 -Dgpg.passphrase=XXXXXX"
# copy prepared workspace (to continue faster if an upload fails in the next step)
----

* If something fails you may switch to the master branch, fix whatever is needed and rebase your release branch to
  accommodate the latest changes done.
* On success you can check the release packages from `dist/target`.
* If everything looks good you can proceed with the release:

[listing,text]
----
$ export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=200m"
$ mvn release:prepare -DperformRelease=true
$ mvn release:perform -DperformRelease=true
----

=== Preparing the release without the Release Plugin

The release plugin is great, but in some cases it breaks even, when release:prepare -DdryRun=true was successful.
Preparing the release vote without the release plugin is stright forward:

* As described checkout a release branch of the current head
* Then us maven and git commands to prepare the release:

[listing,text]
----
$ git checkout -b vote-tamaya-[release version]
$ export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=200m"
$ mvn versions:set versions:commit -DnewVersion=[release version] -DperformRelease=true
# build the release locally and sign it with your certs
$ mvn clean install -DperformRelease=true -Dgpg.keyname=1336D3E6 -Dgpg.passphrase=XXXXXX
----

* Check if everything is in place and correct, when finished you can tag and deploy the release...

[listing,text]
----
$ mvn deploy -DperformRelease=true -Dgpg.keyname=1336D3E6 -Dgpg.passphrase=XXXXXX
----

* check the created commits including user-name and email
* login to https://repository.apache.org/[^] and go to "Staging Repositories"
* check the contents of the newly created tamaya staging repository
* _close_ the repository to let Nexus do its validations
* On success:
* push the release-branch to the git repo

[listing,text]
----
$ git add -A
$ git commit -m "Release Prepare: Set release version."
$ git tag vote01-[release-version]
$ git push --tags
----

Finally open the next development version:

[listing,text]
----
# example: newVersion=0.3-incubating-SNAPSHOT
$ mvn version:set versions:commit -DnewVersion=[development-version]
$ git add -A
$ git commit -m "Release Prepare: Open new development version."
----



* Add the distribution artifacts to the dev repositories:

[listing,text]
----
$ svn co https://dist.apache.org/repos/dist/dev/incubator/tamaya/
$ mkdir [version]
$ set RELEASE_HOME='pwd'/[version]
$ cd PROJECT_ROOT
$ cp DISCLAIMER $RELEASE_HOME
$ cp NOTICE $RELEASE_HOME
$ cp LICENCE $RELEASE_HOME
$ cp rat.txt $RELEASE_HOME
# Copy everything from
#  $STAGING_REPO/distribution/0.2-incubating/tamaya-distribution-[version]-distribution-* into $RELEASE_HOME
$ svn add [version]
$ svn commit --username <apacheId>
----

* Check contents on https://dist.apache.org/repos/dist/dev/incubator/tamaya/[version]


== Start the vote

[listing,text]
----
[VOTE] Release of Apache Tamaya [version]

Hi,

I was running the needed tasks to get the [version] release of Apache Tamaya out.
The artifacts are deployed to Nexus [1] (and [2]) and releases [4].

The tag is available at [3] and will renamed once the vote passed.

Please take a look at the artifacts and vote!

Please note:
This vote is a "majority approval" with a minimum of three +1 votes (see [5]).

------------------------------------------------
[ ] +1 for community members who have reviewed the bits
[ ] +0
[ ] -1 for fatal flaws that should cause these bits not to be released, and why..............
------------------------------------------------

Thanks,
[name]

[1] https://repository.apache.org/content/repositories/...
[2] https://repository.apache.org/content/repositories/org/apache/tamaya/tamaya-distribution/[version]/tamaya-[version]-source-release.zip
    https://repository.apache.org/content/repositories/org/apache/tamaya/tamaya-distribution/[version]/tamaya-[version]-bin-release.zip
[3] https://git1-us-west.apache.org/repos/asf?p=incubator-tamaya.git;a=commit;h=2910da468fce16210e6dd77d8ba23ddbdd434efe
[4] https://dist.apache.org/repos/dist/dev/incubator/tamaya/[release-version]
[5] http://www.apache.org/foundation/voting.html#ReleaseVotes
----

* Announce the Vote
  ** Create a short link to the release at http://s.apache.org (format Tamaya_[version])
  ** Tweet about the vote via _@TamayaConf_

* After 72 hours close the vote write a reult email, e.g.

[listing,text]
----
[Result] (was: Re: [VOTE] Release of Apache Tamaya [version])

Thank you for voting!

X binding +1 votes (pmc):
[list]

Y non-binding +1 votes:
[list]

Z -1 votes
[list]
----

* After the vote on the PPMC has been finished and is successful, repeat the voting process on the
  incubator mailing list.


== Perform the release

If the binding majority approved the vote on both lists continue:

* Login to https://repository.apache.org/ and _release_ the repository
* Rename the vote branch:

[listing,text]
----
$ git branch -m vote01-tamaya-[release-version] tamaya-[release-version]
----

* Add a release tag:

----
$ git tag -a tamaya-[release-version]
----

* Merge master with the new prepared version:

[listing,text]
----
$ git checkout master
$ git merge tamaya-[release-version]
$ git push origin tamaya-[release-version]
$ git push origin master
----

* Close the release and corresponding tickets at JIRA

* Wait some minutes and check http://repo2.maven.org/maven2/org/apache/tamaya[^]

* Upload the distribution Artifacts

[listing,text]
----
$ svn co https://dist.apache.org/repos/dist/release/incubator/tamaya/
$ mkdir [version]
# add and commit the artifacts (*source-release.zip, *bin-release.zip + asc, md5, sha1)
# use the artifacts from:
# http://repo1.maven.org/maven2/org/apache/tamaya/tamaya-distribution/[version]/
----


== Updating the Tamaya Project Site

Basically the new site should be directly deployable, just execute

[listing,text]
----
$ mvn site site:deploy
----


== Announce the new version

Announce the new version on @TamayaConf and other social media channels.
Also drop a short mail on the mailing list.
