:jbake-type: page
:jbake-status: published

= Apache Tamaya -- Extension: JodaTime

toc::[]

[[Core]]
== Tamaya JodaTime (Extension Module)

=== Overview

Tamaya JodaTime is an extension module to support the usage of http://www.joda.org/joda-time/[Joda-Time]
in conjunction with Tamaya. Tamaya JodaTime defines some additional property
converters to retrieve Joda-Time types from a given configuration.

Refer to the link:../extensions.html[extensions documentation] for further details
about modules.

tools to locate resources in your classpath or file system based on descriptive
ant-styled resource patterns. To use this module add the following dependency:

[source, listing]
-----------------------------------------------
<dependency>
  <grooupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-jodatime</artifactId>
  <version>{tamaya_version}</version>
</dependency>
-----------------------------------------------

After adding this dependency to your project you can retrieve
Joda-Time based values directly from a given configuration.

[source,java]
-----------------------------------------------
Configuration configuration = ConfigurationProvider.getConfiguration();

DateTime pit = configuration.get("pointInTime", DateTime.class)
-----------------------------------------------

=== Specifying date and time values

To be written.

=== Specifing periods and durations

To be written.
