:jbake-type: page
:jbake-status: published

= Apache Tamaya -- Extension: Classloader Isolation Support

toc::[]


[[Environment]]
== Tamaya Environment Model (Extension Module)

Tamaya _Environment_ is an extension module. Refer to the link:../extensions.html[extensions documentation] for further details.

=== What functionality this module provides ?

The Tamaya _Environment_ extension adds a simple PropertySourceProvider that evaluates a List of environment context and
combines them in the given order into an (optional) root context within the system's configuration.


=== Compatibility

The module is based on Java 7, so it will not run on Java 7 and beyond.


=== Installation

To benefit from Tamaya Environment Model you only must add the corresponding dependency to your module:

[source, xml]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-envionment</artifactId>
  <version>{tamaya_version}</version>
</dependency>
-----------------------------------------------


=== How it Works

tbd

=== Reusable Base Classes

tbd
