:jbake-type: page
:jbake-status: published

= Apache Tamaya -- Extensions: OSGI Integrations

toc::[]


[[Optional]]
== Tamaya OSGI Support
=== Overview

Tamaya provides also support for integration with OSGI. Hereby Tamaya implements the OSGI +ConfigAdmin+ service,
which is the OSGI basic component providing configuration. Tamaya by default overrides the OSGI default configuration
but can also be configured to extend it.


=== Compatibility

All module described are based on Java 7, so it will run on Java 7 and beyond.
The modules are built against OSGI Compendium version 5.0. Tamaya OSGI support is tested against the following OSGI
runtimes:

* Apache Karaf, version 4.0.7
* tbd: Apache Felix, version x.x.x.
* tbd: Eclipse Equinox, version x.x.x.


=== Installation

To benefit from Tamaya in an OSGI context you must deploy at least the following modules to your OSGI runtime
environment:

[source, listing]
-----------------------------------------------
# API and core
org.apache.tamaya:tamaya-api:{tamaya_version}
org.apache.geronimo.specs:geronimo-annotation_1.2_spec:1.0-alpha-1
org.apache.tamaya:tamaya-core:{tamaya_version}
org.apache.tamaya.ext:tamaya-functions:{tamaya_version}
org.apache.tamaya.ext:tamaya-osgi:{tamaya_version}
-----------------------------------------------


=== How Tamaya deals with OSGI Specialities

Important to know is that within OSGI class- and resource loading is not compatible with standard Java SE. Also bundle can
be loaded or unloaded at any time, so Tamaya's logic should not assume a stable non changing environment.
These constraints are handled by Tamaya (implemented in +tamaya-core+ and +tamaya-psgi+) as follows:

* Tamaya registers a +ServiceListener+ which reads all +java.util.ServiceLoader+ configurations and
  registers them as OSGI services. Hereby integration is two-way: The core module contains an
  OSGI +Activator+ that replaces the default +ServiceContext+ with an OSGI based +ServiceContext+ that
  will consume all services through the OSGI service API. Consequently you can also register Tamaya extensions
  as OSGI services yourself (e.g. your own +PropertySource+ instances).
* Tamaya's +ServiceContext+ SPI does not only provide a facade to the OSGI service mechanism it also provides
  an API for loading of (classpath) resources. In OSGI it delegates to the bundle's +getEntry(String)+ method.

Finally by adding Tamaya's OSGI integration module (+tamaya-osgi+) Tamaya replaces the existing OSGI +ConfigAdmin+ service
with an istance based on Tamaya. Hereby Tamaya can use the existing +ConfigAdmin+ component as a fallback
or override source (see configuration options explained later). This does not interfere with any existing
injection mechanism already in place in your existing OSGI environment.


=== Configuring how Tamaya integrates with the existing ConfigAdmin service

Tamaya provides several options that define how it combines it's values with the values provided
from the additionally installed +ConfigAdmin+ service:

* +org.tamaya.integration.osgi.cm.ranking+ (int) allows to configure the OSGI service ranking used by the Tamaya
  +BundleActivator+ to register Tamaya's +ConfigAdmin+ service. In OSGI higher ranking precede lower rankings.
  By default Tamaya's OSGI extending service registration mechanism is reusing any annotated +@Priority+ priority
  values as corresponsing rankings.
* +org.tamaya.integration.osgi.cm.override+ (boolean) allows to configure if Tamaya is overriding any existing
  values from the default +ConfigAdmin+ instance, or only extending them. In other words this setting allows you to
  define, which configuration subsystem has precedence for evaluating the final values, either Tamaya based
  configuration (default) or the configuration mechanisms provided by default from your OSGI container (when this flag
  is set to +false+).


=== Mapping of pids and factoryPids

When accessing configuration from the OSGI +ConfigAdmin+ a pid, or factoryPid is passed additionally to
tell the configuration service, for which bundle configuration is requested. Tamaya, by default, maps
the OSGI pid or factory pid to a corresponding root section in Tamaya's configuration:

[source, listing]
.OSGI default pid mapping
-----------------------------------------------
# OSGI parameters
pid=myBundle
key=common.net.port

# Tamaya key
[myBundle]common.net.port
-----------------------------------------------

This mapping can be adapted if needed by implementing and registering the following OSGI service:

[source, java]
.OSGIConfigRootMapper
-----------------------------------------------
public interface OSGIConfigRootMapper {

    String getTamayaConfigRoot(String pid, String factoryPid);
}
-----------------------------------------------


== Tamaya based Injection

=== Overview

OSGI itself already provides injection and configuration mechanism. Since Tamaya is working in the back
you can continue to use the mechanism of your choice. Nevertheless Tamaya also supports enabling Tamaya
specific configuration injection.


=== Installation

To benefit from Tamaya's injection mechanism in your OSGI services you need additionally to the basic
OSGI support described earlier in this document:

[source, listing]
-----------------------------------------------
org.apache.geronimo.specs:geronimo-atinject_1.0_spec:1.0
org.apache.tamaya.ext:tamaya-inject-api:{tamaya_version}
org.apache.tamaya.ext:tamaya-inject-se:{tamaya_version}
org.apache.tamaya.ext:tamaya-inject-osgi:{tamaya_version}
-----------------------------------------------


=== Example

As an example, what is possible you can implement and register an OSGI service and use Tamaya's injection
API for configuring it:

[source, java]
-----------------------------------------------
public class HelloServiceImpl implements HelloService{

    @Config(value={"example.message"}, defaultValue="A Tamaya default.")
    private String message;

    @Override
    public String sayHello() {
        System.err.println("HELLO: " + message);
        return message;
    }
}
-----------------------------------------------

