:jbake-type: page
:jbake-status: published

= Apache Tamaya - Extension: Functions

toc::[]

[[Functions]]
== Tamaya Functions (Extension Module)

Tamaya _Functions_ is an extension module. Refer to the link:../extensions.html[extensions documentation] for further details.


=== What functionality this module provides ?

Tamaya _Functions_ provides several functional extensions using the +UnaryOperator<Config>,Function<Config, T>+ extension
points. Most functional extension are accessible from the +ConfigurationFunctions+ singleton. Since the JSR API
does not provide any functional extension points it is recommended to adapt the +Config+ instance into .+FunctionalConfig+.
Then, when importing the functional methods statically they can very easily applied, e.g.

[source,java]
-------------------------------------------------------------------
import static org.apache.tamaya.functions.ConfigurationFunctions.*;

FunctionalConfig fc = FunctionalConfig.of(ConfigProvider.getConfig());
Set<String> sections = fc.with(areas("a", false).with(transitiveAreas());
-------------------------------------------------------------------

The expression above returns all fully qualified section names that are child sections of the root section 'a'.
So given the entries +a.b.entry1, a.b.entry2, a.a.entry3, a.b.c.entry4+ the reult would be +a, a.a, a.b, a.b.c+.

=== Compatibility

The module is based on Java 8, so it can be used with Java 8 and beyond.

=== Installation

For using the functionality shown in this document you only must add the corresponding dependency to your module:

[source, xml]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-functions</artifactId>
  <version>{tamaya_version}</version>
</dependency>
-----------------------------------------------


=== FunctionalConfig

The +FunctionalConfig+ actually adds the functional extension points +with+ and +query+ to .+Config+ instance, which
allow to chain expressions as seen in the introductionary snippet:

[source, java]
-----------------------------------------------
public interface FunctionalConfig extends Config, ConfigContextSupplier {

    /**
     * Enriches a {@link Config} instance with functional access points.
     * @param config the config, not null
     * @return a functional config instance.
     */
    static FunctionalConfig of(Config config){
        ...
    }

    default FunctionalConfig with(UnaryOperator<Config> operator);
    default <T> T query(Function<Config, T> query);
}
-----------------------------------------------


=== The Provided Functions

==== Functions on +ConfigurationFunctions+

The following sections explain the provided functions defined by +ConfigurationFunctions+ singleton.

* *UnaryOperator<Config> filter(PropertyMatcher matcher)* creates a +UnaryOperator<Config>+ that creates a +Configuration+
  containing only keys that are selected by the given _matcher predicate_. The +PropertyMatcher+ hereby allows to evaluate not only
  the _key_, but also the _value_.
* *UnaryOperator<Config> map(KeyMapper keyMapper)* creates a +UnaryOperator<Config>+ that maps the keys as defined
  by the given _keyMapper_.
* *UnaryOperator<Config> section(String section)* creates  a +UnaryOperator<Config>+ that creates a +Configuration+ containing only
  entries that are direct or indirect members of the given section.
* *UnaryOperator<Config> section(String areaKey, boolean stripKeys)* creates  a +UnaryOperator<Config>+ that creates a +Configuration+
  containing only entries that are direct or indirect members of the given section. Hereby _stripKeys_ allows to determine
  if the returned entries should be relative to the search criteria {{stripKeys=true}} or absolute keys.
* *isKeyInSection(String section, String sectionKey)* allows to easily determine if a given _key_ is a direct or indirect member
  of a given section.
* *boolean isKeyInSections(String key, String... sectionKeys)* allows to easily determine if one key of given
  _key_ is a direct or indirect member of at least one of the given _sectionKeys_.
* *Function<Config,Set<String>> sections()* allows to query all the contained fully qualified section names (the ones that
  also have parameters present).
* *Function<Config,Set<String>> transitiveSections()* allows to query all the contained fully qualified section names,
  including the transitive closure of sections.
* *Function<Config,Set<String>> sections(final Predicate<String> predicate)* allows to query all the contained fully
  qualified section names that are selected by the given _predicate_.
* *Function<Config,Set<String>> sections(final Predicate<String> predicate)* allows to query all the contained fully
  qualified section names that are selected by the given _predicate_, including the transitive closure of sections
  identified.
* *UnaryOperator<Config> sectionsRecursive(String... sectionKeys)* provides a +UnaryOperator<Config>+ that filters all sections identified
  by the given _sectionKeys_ and its child sections.
* *UnaryOperator<Config> sectionRecursive(final boolean stripKeys, final String... sectionKeys)* provides a +UnaryOperator<Config>+
  that filters all sections identified by the given _sectionKeys_ and its child sections. _stripKeys_ allows to
  determine if the resulting configuration should be relative to the selected areas ({{stripKeys=true}}) or
  absolute (filtering only).
* *Function<Config,String> jsonInfo()* returns a query that converts a +Configuration+ into a JSON formatted +String+
  representation.


==== Functions on +ConfigSourceFunctions+

The following sections explain the provided functions defined by +ConfigSourceFunctions+ singleton.

* *ConfigSource addMetaData(ConfigSource propertySource, Map<String,String> metaData)* Creates a new +ConfigSource+
  with the given metadata added.
* *boolean isKeyInSection(String key, String sectionKey)* Checks if the given _key_ is a direct or indirect member of
  one of the given _sectionKey_.
* *boolean isKeyInSections(String key, String... sectionKeys)* Checks if the given _key_ is a direct or indirect member of
   one of one of the given _sectionKeys_.
* *Set<String> sections(Map<String, String> properties)* Extracts the sections from the given properties.
* *Set<String> transitiveSections(Map<String, String> properties)* Extracts the transitive sections from the given
  properties.
* *Set<String> sections(Map<String, String> properties, final Predicate<String> predicate)* Extracts the sections
  from the given properties, also filtering with the given predicate.
* *Set<String> transitiveSections(Map<String, String> properties, Predicate<String> predicate)* Extracts the transitive
  sections from the given properties, also filtering with the given predicate.
* *Map<String,String> sectionsRecursive(Map<String, String> properties, String... sectionKeys)* Creates w +ConfigSource+
  only containing the sections that a direct or indirect children of the given _sectionKeys_.
* *Map<String,String> sectionRecursive(Map<String, String> properties, boolean stripKeys, String... sectionKeys)* Creates w +ConfigSource+
  only containing the sections that a direct or indirect children of the given _sectionKeys_. With _stripKeys_ one can
  select of the returned values should be relative to its selection of be fully qualified.
* *String stripSectionKeys(String key, String... sectionKeys)* This function strips away the matching section key as given
  in _sectionKeys_ from a given _key_.
