:jbake-type: page
:jbake-status: published

= Apache Tamaya - Extension: Events

toc::[]


[[Events]]
== Tamaya Events (Extension Module)

Tamaya _Events_ is an extension module. Refer to the link:../extensions.html[extensions documentation] for further details.

=== What functionality this module provides ?

Tamaya _Events_ provides a mechanism to publish and subscribe to +ConfigEvent<T>+ instances.
This module implements +ConfigChange+ or +ConfigSourceChange+ as possible payloads, but
the module itself is not constraint to this payload types.
These payload types describe detected changes of key/values of a +Config+ or a +ConfigSource+.
The extension also provides a _Singleton accessor_ which allows to register/unregister
listeners for changes and the period, when configuration should be scanned for
any changes.

Summarizing with the events module you can easily observe configuration changes, record the
state of any configuration and compare configuration states to create and publish related
change events.

=== Compatibility

The module is based on Java 8, so it can be used with Java 8 and beyond.

=== Installation

To benefit from configuration event support you only must add the corresponding dependency to your module:

[source, xml]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-events</artifactId>
  <version>{tamaya_version}</version>
</dependency>
-----------------------------------------------


=== Core Architecture

The core of the module are the +ConfigEventListener+ and the +ConfigEvent+ interfaces,
which defines an abstraction for event handling and observation:

[source,java]
.ConfigEvent
--------------------------------------------
public interface ConfigEvent<T> {

    Class<T> getResourceType();
    T getResource();
    String getVersion();
    long getTimestamp();
}

@FunctionalInterface
public interface ConfigEventListener {

    void onConfigEvent(ConfigEvent<?> event);

}
--------------------------------------------

Hereby the payload _T_ can be basically of an arbitrary type as long as
it implements the +ConfigEvent+ interface. The next sections
give more details on the the event types provided by this extension
and their usage.

Also the technology to be used for publishing these event types is adaptable.
In SE the module uses a simple in-memory implementation based on the
Google _Guava_ library. But users can replace this mechanism as needed. For
more details refer to the SPI section later in this guide.


=== The ConfigEventManager Singleton

Main entry point of the events module is the +ConfigEventManager+ singleton class, which provides static accessor
methods to the extension's functionality:

* _Adding/removing_ of +ConfigChangeListener+ instances, either globally or per event type.
* _Firing configuration events_ synchronously or asyncronously (mostly called by framework code).
* _Configuring the monitor_ that periodically checks for changes on the global +Configuration+ provided
  by +ConfigurationProvider.getConfiguration()+.

[source,java]
-------------------------------------------------------
public final class ConfigEventManager {

    private ConfigEventManager() {}

    public static void addListener(ConfigEventListener l);
    public static <T extends ConfigEvent> void addListener(ConfigEventListener l, Class<T> eventType);
    public static void removeListener(ConfigEventListener l);
    public static <T extends ConfigEvent> void removeListener(ConfigEventListener l, Class<T> eventType);
    public static <T extends ConfigEvent>
        Collection<? extends ConfigEventListener> getListeners();
    public static <T extends ConfigEvent>
        Collection<? extends ConfigEventListener> getListeners(Class<T> type);

    public static <T> void fireEvent(ConfigEvent<?> event);
    public static <T> void fireEventAsynch(ConfigEvent<?> event);

    public static void enableChangeMonitoring(boolean enable);
    public static boolean isChangeMonitoring();
    public long getChangeMonitoringPeriod();
    public void setChangeMonitoringPeriod(long millis);

}
-------------------------------------------------------


=== Modelling configuration changes as events

This module provides a serializable and thread-safe abstraction modelling a
configuration change, which is anything of the following

* additional, _new_ configuration entries
* _removed_ configuration entries
* _changes_ on existing entries


A collection of changes

* on a +Config+ is modelled by the +ConfigChange+ class
* on a +ConfigSource+ is modelled by the +ConfigSourceChange+ class


==== Configuration Changes

A set of changes on a +Config+ is described by a +ConfigChange+
as follows:

[source,java]
-------------------------------------------------------
public final class ConfigChange implements ConfigEvent<Config>, Serializable{

    public static ConfigChange emptyChangeSet(Config configuration);

    @Override
    public Config getResource();
    @Override
    public Class<Config> getResourceType();
    @Override
    public String getVersion();
    @Override
    public long getTimestamp();

    // Event specific methods

    public Collection<PropertyChangeEvent> getChanges();
    public int getRemovedSize();
    public int getAddedSize();
    public int getUpdatedSize();

    public boolean isKeyAffected(String key);
    public boolean isRemoved(String key);
    public boolean isAdded(String key);
    public boolean isUpdated(String key);
    public boolean containsKey(String key);
    public boolean isEmpty();
}

-------------------------------------------------------

New instances of +ConfignChange+ hereby can be created using a
fluent +ConfigChangeBuilder+:

[source,java]
-------------------------------------------------------
Config config = ...;
ConfigChange change = ConfigChangeBuilder.of(config)
  .addChange("MyKey", "newValue")
  .removeKeys("myRemovedKey").build();
-------------------------------------------------------

Also it is possible to directly compare 2 instances of +Config+,
which results in a +ConfigChange+ that
reflects the differences between the two configurations passed:

[source,java]
Comparing 2 configurations
-------------------------------------------------------
Config config = ...;
Config changedConfig = ...;
ConfigChange change = ConfigChangeBuilder.of(config)
  .addChanges(changedConfig).build();
-------------------------------------------------------

So a +ConfigChange+ describes all the changes detected on a +Config+.
This allows you to publish instances of this class as events to all registered
listeners (observer pattern).
For listening to +ConfigChange+ events you must implement the
+ConfigEventListener+ functional interface:

[source,java]
.Implementing a ConfigChangeListener
-------------------------------------------------------
public final class MyConfigChangeListener implements ConfigEventListener<ConfigChange>{

  private Config config = ConfigProvider.getConfig();

  public void onConfigEvent(ConfigEvent<?> event){
     if(event.getResourceType()==Config.class){
         if(event.getConfiguration()==config){
           // do something
         }
     }
  }

}
-------------------------------------------------------

You can *register* your implementation as illustrated below:

. Manually by calling +ConfigEventManager.addListener(new MyConfigChangeListener())+
. Automatically by registering your listener using the +ServiceLoader+ under
  +META-INF/services/org.apache.tamaya.events.ConfigEventListener+

Registering programmatically also allows you to define additional constraint,
to filter out all kind of events you are not interested in.

NOTE: By default detection of configuration changes is not enabled. To enable it, call
+ConfigEventManager.enableChangeMonitoring(true)+.


=== ConfigSource Changes

Beside that a whole +Config+ changes, also a +ConfigSource+ can change,
e.g. by a configuration file edited on the fly. This is similarly to a
+ConfigChange+ reflected by the classes +ConfigSourceChange,
ConfigSourceChangeBuilder+.


==== Monitoring of configuration changes

The +ConfigEventManager+ supports *active monitoring of the current configuration* to trigger corresponding change
events to listeners registered. *This feature is deactivated by default*, but can be enabled by calling
+ConfigEventManager.enableChangeMonitoring(true);+. This feature avoids regularly polling your local +Config+ for
any kind of changes. If a change has been encountered Tamaya identifies it and triggers corresponding
+ConfigChange+ events automatically.


=== Freezing Configs and ConfigSources

+Config+ instances as well as +ConfigSources+ are explicitly not required to be serializable. To enable easy
serialization of these types a +Config+'s *current state can be frozen* (e.g. for later comparison with a newly
loaded version). Freezing hereby means

* all key/values are read-out by calling the +getProperties()+ method.
* a meta data entry is added of the form +_frozenAt=223273777652325677+, whichdefines the UTC timestamp in
  milliseconds when this instance was frozen.
* if not already defined an +_id+ property will be added to the +Config+ containing the
  identifier of the configuration.

In code freezing is a no-brainer:

[source,java]
.Freezing the current Config
--------------------------------------------------
Config config = ConfigProvider.getConfig();
Config frozenConfig = FrozenConfig.of(config);
--------------------------------------------------

... and similarly for a +ConfigSource+:

[source,java]
.Freezing a ConfigSource
--------------------------------------------------
ConfigSource configSource = ...;
ConfigSource frozenSource = FrozenConfigSource.of(configSource);
--------------------------------------------------



=== SPIs

This component also defines SPIs, which allows to adapt the implementation of the main +ConfigEventManager+
singleton. This enables, for example, using external eventing systems, such as CDI, instead of the default provided
simple SE based implementation. By default implementations must be registered using the current +ServiceContext+
active (by default using the Java +ServiceLoader+ mechanism).

[source,java]
.SPI: ConfigEventSpi
--------------------------------------------------
public interface ConfigEventManagerSpi {

        <T> void addListener(ConfigEventListener l);
        <T extends ConfigEvent> void addListener(ConfigEventListener l, Class<T> eventType);
        void removeListener(ConfigEventListener l);
        <T extends ConfigEvent> void removeListener(ConfigEventListener l, Class<T> eventType);
        Collection<? extends ConfigEventListener> getListeners();
        Collection<? extends ConfigEventListener> getListeners(Class<? extends ConfigEvent> eventType);

        void fireEvent(ConfigEvent<?> event);
        void fireEventAsynch(ConfigEvent<?> event);

        long getChangeMonitoringPeriod();
        void setChangeMonitoringPeriod(long millis);
        boolean isChangeMonitorActive();
        void enableChangeMonitor(boolean enable);
}
--------------------------------------------------
