:jbake-type: page
:jbake-status: published

= Apache Tamaya - Extension: User Filtering

toc::[]


[[Filter]]
== User Filtering (Extension Module)

Tamaya _Filter_ is an extension module. Refer to the link:../extensions.html[extensions documentation] for further details.


=== What functionality this module provides ?

Tamaya _Filter_ provides a simple singleton accessor that allows to explicitly add +Filter+ instances
active on the current thread only. This can be very useful in many scenarios, especially within
Java EE web filters or similar. Additionally this module adds
standard filters that hide metadata entries when the full configuration map is accessed. When keys are accessed
explicitily no filtering is applied and everything is visible.

=== Compatibility

The module is based on Java 8, so it will not run on Java 8 and beyond.


=== Installation

To benefit from filter support you only must add the corresponding dependency to your module:

[source, xml]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-filter</artifactId>
  <version>{tamaya_version}</version>
</dependency>
-----------------------------------------------


=== The Extensions Provided

Tamaya Filter comes basically with 3 artifacts:

* The +org.apache.tamaya.filter.ConfigurationFilter+ provides several static methods to register +Filter+
instances on the current thread:

[source, java]
-----------------------------------------------
public final class ConfigurationFilter implements Filter{

    ...

    /**
     * Seactivates metadata filtering also on global map access for this thread.
     * @see #clearFilters()
     * @param active true,to enable metadata filtering (default).
     */
    public static void setFilterMetadata(boolean active);

    /**
     * Access the filtering configuration that is used for filtering single property values accessed.
     * @return the filtering config, never null.
     */
    public static FilterContext getSingleFilterContext();

    /**
     * Access the filtering configuration that is used for filtering configuration properties accessed as full
     * map.
     * @return the filtering config, never null.
     */
    public static FilterContext getMapFilters();

    /**
     * Removes all programmable filters active on the current thread.
     */
    public static void clearFilters();

    ...

}
-----------------------------------------------

For using regular expression when filtering configuration keys a corresponding implementation of a +PropertyFilter+
is part of this module, So you can add a customized filter as follows:

[source, java]
-----------------------------------------------
try {
    ConfigurationFilter.getMapFilters().addFilter(new myFilter());

    // do your code with filtering active
}
finally {
    // cleanup
    ConfigurationFilter.clearFilters();
}
-----------------------------------------------


The +FilterChain+ is a simple compound structure combining multiple filters into one new (chained) filter:

[source, java]
-----------------------------------------------
public final class FilterChain implements Filter {

    public void addFilter(Filter filter);
    public void addFilter(int pos, Filter filter);
    public Filter removeFilter(int pos);
    public void clearFilters();
    public void setFilters(Filter... filters);
    public void setFilters(Collection<Filter> filters);
    public List<Filter> getFilters();

}
-----------------------------------------------
