:jbake-type: page
:jbake-status: published

= Apache Tamaya - Extension: Integration with Hazelcast

toc::[]


[[Consul]]
== Integration with Hazelcast (Extension Module)

Tamaya _Hazelcast_ is an extension module. Refer to the link:../extensions.html[extensions documentation] for further details.


=== What functionality this module provides ?

Tamaya _Hazelcast_ provides a property source which uses
link:http://www.hazelcast.org[Hazelcast] as configuration backend. Hereby the
module supports read-only integration (as a +HazelcastConfigSource+ as well
as a writing configuration changes back (based on Tamaya's +MutableConfiguration+ API
defined by the link:mod_mutable_config.html[tamaya-mutable-config] extension module.


=== Compatibility

The module is based on Java 8, so it will not run on Java 8 and beyond.


=== Installation

To use _tamaya-hazelcast_ you only must add the corresponding dependency to your module:

[source, xml]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-hazelcast</artifactId>
  <version>{tamaya_version}</version>
</dependency>
-----------------------------------------------


=== The Extensions Provided

Hazelcast integration comes basically with 2 artifacts:

* The +org.apache.tamaya.hazelcast.HazelcastConfigSource+ is a +ConfigSource+. The property source is not automatically
  registered. Either register it using the _ServiceLoader_ yourself or implement
  and register a corresponding `ConfigSourceProvider`.
* If the +tamaya-mutable-config+ module is loaded it is possible to write property values back into the consul cluster,
  by accessing a +MutableConfiguration+ using the URI +config:hazelcast+.

Access of consul key/value pairs is through the normal Tamaya API.


=== The HazelcastConfigSource

The +HazelcastConfigSource+ is not automatically registered and provides different options how to integrate
Tamaya with Hazelcast.

[source, java]
-----------------------------------------------
/**
 * Creates a new instance, hereby using {@code "Hazelcast"} as property source name and
 * a default hazelcast backend created by calling {@link Hazelcast#newHazelcastInstance()}.
 */
public HazelcastConfigSource();

/**
 * Creates a new instance, hereby using {@code "Hazelcast"} as property source name and the
 * given hazelcast instance.
 * @param hazelcastInstance the hazelcast instance, not null.
 */
public HazelcastConfigSource(HazelcastInstance hazelcastInstance);

/**
 * Creates a new instance, hereby using the given property source name and
 * a default hazelcast backend created by calling {@link Hazelcast#newHazelcastInstance()}.
 * @param name the property source name, not null.
 */
public HazelcastConfigSource(String name);

/**
 * Creates a new instance, hereby using the given property source name and
 * a creating a new hazelcast backend using the given Hazelcast {@link Config}.
 * @param config the hazelcast config, not null.
 * @param name the property source name, not null.
 */
public HazelcastConfigSource(String name, Config config);

/**
 * Creates a new instance, hereby using the given property source name and the
 * hazelcast instance.
 * @param name
 * @param hazelcastInstance
 */
public HazelcastConfigSource(String name, HazelcastInstance hazelcastInstance);
-----------------------------------------------

To use hazelcast as a configuration backend, you simply create the corresponding Hazelcast instance
and use it to initialize the Tamaya property source. Given that a hazelcast backedn configuration
can be easily created asillustrated below:

[source, java]
-----------------------------------------------
// define config settings
HazelcastInstance hazelcastInstance = Hazelcast.newInstance(hazelcastConfig);
HazelcastConfigSource cs = new HazelcastConfigSource(hazelcastInstance);
cs.setName("myHazelcast-config");
cs.setOrdinal(2000);
// Build your own configuration
ConfigBuilder b = ConfigProviderResolver.getInstance().getBuilder();
b.addDiscoveredConverters().addDefaultSources().addDiscoveredSources();
// Add the hazelcast property source (as most significant)
b.awithSource(cs);
// build and use the configuration
Config config = b.build();
-----------------------------------------------
