:jbake-type: page
:jbake-status: published

= Apache Tamaya: Base Module

toc::[]


[[SPISupport]]
== Tamaya Base

Tamaya _Base_ is a core module only depending on the ConfigJSR API. It implements various API and SPI related
artifacts in a portable way. Tamaya's core module reuses this functionality to build up a fully fledged
Tamaya ConfigJSR API implementatation.

=== What functionality does this module provide?

Tamaya _Base_ provides a few helpful base classes that can be used to implement aspects of a Configuration system:

* +BaseConfigSource+ provides an abstract *base class* for implementation of your own ConfigSources.
* +DefaultConfig+ provides you with a simple implementation of the +Config+ interface. This is also very useful
  for mocking configuration during test execution, but not only constraint to that use case.
* An +EnumConverter+,that is a converter implementation that can automatically select the currect enumeration values based
  on a configured entry.
* +MapConfigSource+ implements a config source based on +java.util.Map+.
* +PriorityServiceComparator+ compares arbitrary services based on their +@Priority+ annotations (also handling the
  case, where no such annotation is present).
* +PropertiesResourceConfigSource+ is an implementation of a +ConfigSource+ based on a +Properties+ instance,
  loadable from any +URL+.
+ +ConverterManager+ is a useful service class managing registered instances of +Converter+. It provides a simple
  way to use type conversion logic.
+ +Filter+ allow interception of evaluated config values before they get passed to any type conversion logic.
+ +FilterContext+ provides another helpful class that manages +Filter+ instances and provides an
  easy to use high level API.
+ +ConfigSourceComparator+ provides an implementation that compares +ConfigSources+ based on their +getOrdinal()+
  values and their class names.

NOTE: It is highly recommended that you also read the link:../core.html[documentation] of Tamaya's
      core implementation, since this describes the abstrations in use in more
      detail. This module allows to reuse Tamaya's implementation artifacts but
      still allows alternate implementations of the core API to be used.

=== Compatibility

The module is based on Java 8, so it will run on Java 8 and beyond.


=== Installation

To use Tamaya's _Base_ you only have to add the corresponding dependency to your module:

[source, xml]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya</groupId>
  <artifactId>tamaya-base</artifactId>
  <version>{tamaya_version}</version>
</dependency>
-----------------------------------------------

The component will not register any components but only provides portable base classes for some common SPI
implementation tasks. It only depends on the API, so it should be safely reusable also with other implementations
of the Tamaya API as well.
